In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
file_path = "/content/drive/MyDrive/23-1 ITS 데이터 분석 스터디 : 프로젝트 1팀/데이터 아카이브/전처리 완료 데이터/"
file_name_score = "합친파일_완성본.csv"
file_name_given = "제시 데이터 전처리 완료(2).csv"

df_score = pd.read_csv(file_path + file_name_score, encoding='cp949')
df_given = pd.read_csv(file_path + file_name_given, encoding='cp949')

df_score.set_index("종목", inplace=True)
df_score = df_score.transpose()
df_score.columns

Index([     '소비자물가지수(단일)',     '총지수 (신선식품지수)',    '신선식품 (신선식품지수)',
          '신선어개 (신선식품지수)',    '신선채소 (신선식품지수)',    '신선과실 (신선식품지수)',
        '신선식품제외 (신선식품지수)',     '총지수 (수입물가지수)',      '과일 (수입물가지수)',
          '냉동채소 (수입물가지수)',     '쇠고기 (수입물가지수)',    '돼지고기 (수입물가지수)',
           '닭고기 (수입물가지수)',   '신선수산물 (수입물가지수)',   '냉동수산물 (수입물가지수)',
         '총지수 (품목별소비자물가)',    '배추 (품목별소비자물가)',    '상추 (품목별소비자물가)',
          '오이 (품목별소비자물가)',    '호박 (품목별소비자물가)',    '양파 (품목별소비자물가)',
          '사과 (품목별소비자물가)',     '배 (품목별소비자물가)',  '돼지고기 (품목별소비자물가)',
         '닭고기 (품목별소비자물가)',    '달걀 (품목별소비자물가)',    '갈치 (품목별소비자물가)',
          '명태 (품목별소비자물가)',    '조기 (품목별소비자물가)',   '고등어 (품목별소비자물가)',
          '총지수 (생산자물가지수)',     '배추 (생산자물가지수)',     '상추 (생산자물가지수)',
           '오이 (생산자물가지수)',     '호박 (생산자물가지수)',     '양파 (생산자물가지수)',
           '사과 (생산자물가지수)',      '배 (생산자물가지수)',    '쇠고기 (생산자물가지수)',
         '돼지고기 (생산자물가지수)',    '닭고기 (생산자물가지수)',     '달걀 (생산자물가지수)',
           '조기 (생산자물가지수)',     '갈치 (생산자물가지수)',    '고등어 (생산자물가지수)',
         '기타어류 (생산자물가지수)',   '물오징어 (생산자물가지수)', 'Food Price Index',
                   'Meat',            'Dairy',          'Cereals',
                   'Oils',            'Sugar',           '생활물가지수',
                     '식품',            '식품 이외',              '전월세',
          '전·월세포함 생활물가지수',                nan],
      dtype='object', name='종목')

In [ ]:
df_given.columns

Index(['년도-월', '무', '고등어', '닭고기', '양파', '배추', '냉동참조기', '오징어', '조기', '애호박',
       '사과', '동태', '호박', '배', '쇠고기', '달걀', '상추', '돼지고기', '오이', '명태'],
      dtype='object')

In [ ]:
include_arr = ['년도-월','상추', '호박', '닭고기', '돼지고기', '애호박', '양파', '배', '달걀', '무', '오징어', '고등어', '사과', '오이']
df_given = df_given[include_arr]
print(df_given.columns)
df_given

Index(['년도-월', '상추', '호박', '닭고기', '돼지고기', '애호박', '양파', '배', '달걀', '무', '오징어',
       '고등어', '사과', '오이'],
      dtype='object')

,년도-월,상추,호박,닭고기,돼지고기,애호박,양파,배,달걀,무,오징어,고등어,사과,오이
0,2018-01,1336.262626,2068.648649,5942.083333,12790.315789,2222.377049,3562.474747,2899.890000,4252.005102,1716.200000,3998.865979,3842.258065,1813.230000,991.630000
1,2018-02,1141.217822,2024.594595,6079.690722,13177.525773,2044.193548,3462.000000,3321.143564,4214.560606,2454.808081,3808.091837,3696.774194,1968.178218,824.090000
2,2018-03,1006.111111,2036.951220,6135.204082,13084.432990,2033.333333,3232.161616,3256.914573,3745.994949,2498.865979,3803.552083,3969.326087,1802.787879,724.383838
3,2018-04,942.686869,1393.170732,6072.572917,13087.368421,1386.525424,3182.787879,3309.874372,3708.994898,2653.084211,3934.795918,3379.795455,1825.581633,588.320000
4,2018-05,957.470000,1579.268293,6102.693878,13626.104167,1573.135593,2995.440000,2863.055276,3615.611111,2410.752577,3746.010101,3398.426966,1843.191919,633.131313
5,2018-06,850.710000,1095.000000,5977.326316,14135.063830,1083.965517,2901.606061,2772.365000,3446.373737,1934.226804,3698.835052,3512.954545,1870.393939,535.585859
6,2018-07,1085.494949,1074.634146,6144.896907,14957.543478,949.824561,2921.696970,3700.489899,3598.865979,2385.104167,3898.175258,3251.838710,1808.591837,674.373737
7,2018-08,1653.156250,1749.285714,6502.734043,14859.782609,1786.666667,2971.848485,3896.858065,3962.229592,3102.535211,4173.568421,3423.219780,1944.680412,1002.412371
8,2018-09,1812.855670,1602.272727,6315.869565,14370.978261,1555.754717,2983.160000,4062.946809,4107.076142,3008.888889,3911.041237,3318.648352,2294.877551,834.757576
9,2018-10,1061.180000,1349.204545,6437.135417,13724.893617,1306.842105,2867.099010,3109.641791,4043.560606,2006.229167,4393.978495,3212.769231,1943.178218,699.820000
10,2018-11,946.870000,1563.977273,6265.635417,12529.375000,1507.363636,2873.980000,2767.653061,3976.274112,1659.696970,4582.625000,3128.107527,1759.224490,766.989796
11,2018-12,975.530000,1622.558140,6353.191489,13371.875000,1705.535714,2865.150000,2956.234694,3957.326531,1617.474747,4425.651163,3420.414894,1871.181818,868.570000
12,2019-01,967.039604,1833.720930,6584.840426,13030.000000,1816.491228,2771.168317,3043.383838,3831.517588,1494.300000,4174.638298,3149.021505,2056.092784,936.163265
13,2019-02,890.535354,1482.325581,6483.462366,12797.263158,1466.839286,2695.080000,2914.566327,3637.949239,1407.500000,4060.602151,3258.645161,1967.319588,817.775510
14,2019-03,917.430000,1414.431818,6360.688172,12531.041667,1339.821429,2684.727273,2847.954315,3716.801020,1360.800000,4138.333333,3400.924731,1921.463918,762.597938
15,2019-04,918.010221,1235.944882,6300.909091,13175.090265,1144.870482,2983.257679,2821.331029,3903.808862,1408.430034,3965.772809,3477.387640,1930.981067,617.512069
16,2019-05,1018.953654,1187.306202,6311.875236,13353.109462,1064.277228,3018.471530,2868.844424,3921.741818,1494.003559,3733.723949,3451.812133,1923.488414,570.566071
17,2019-06,961.842881,1242.602996,6214.675347,13278.640275,1169.299419,2757.945902,3066.440397,3885.003336,1542.124386,3619.875630,3581.085561,1956.318555,524.008278
18,2019-07,1045.984330,1139.996904,6220.574213,13166.475483,1062.962865,2462.071225,3357.534247,3876.664493,1543.315264,3353.939655,3596.872611,1987.079886,637.878917
19,2019-08,1585.289683,1563.318841,6294.580601,13035.023192,1646.343284,2513.428758,3609.969516,3841.207171,1606.509804,3732.232713,3411.187151,1895.336898,960.015957
20,2019-09,1441.651515,1576.179941,6293.083451,13796.867816,1595.864450,2542.970109,3814.836573,3965.729339,1812.404891,4020.532148,3486.908962,1951.994467,891.359504
21,2019-10,1617.694581,1416.203753,6465.061460,13466.053165,1377.234375,2493.795371,4133.514865,4068.869188,2419.953260,3968.268991,3523.632783,1679.641626,841.843016
22,2019-11,1302.853470,1335.486188,6364.308525,12663.823454,1225.710956,2555.246523,3552.893299,4139.268214,2498.761290,3845.329700,3620.263434,1681.329923,881.584184
23,2019-12,1230.754765,1405.358333,6350.912467,13013.253807,1372.246014,2674.160200,3528.719343,4207.525543,2570.766355,4215.686192,3798.647849,1734.859296,955.549937
24,2020-01,1371.578674,1888.323615,6342.450954,12735.434501,2021.421801,2871.819462,3669.584042,4178.520915,2767.722689,4779.320109,4017.116959,1950.795839,1167.951886
25,2020-02,1437.681319,2018.125000,6379.611765,12440.725275,2152.800000,2944.054945,3709.491803,4106.407821,2579.090909,4584.977273,3974.939024,1843.417582,1154.842697
26,2020-04,1002.970414,1206.150327,6275.269716,13424.348281,1245.148148,3624.234586,3515.377513,4214.271982,1699.897661,4171.506667,3811.107492,1884.237537,654.452416
27,2020-05,986.069492,1111.623616,6271.488160,14734.199301,1115.301538,3583.774744,3667.442539,4196.404456,1626.644295,4133.815700,4011.593692,1983.384486,569.206723
28,2020-06,1076.932785,1186.334254,6301.843658,15644.893010,1220.305040,3481.795014,3620.216851,4190.838977,1717.577808,3350.962759,3977.505443,2181.407407,616.054201
29,2020-07,1376.885514,1314.289100,6397.299625,15178.641371,1352.500000,3252.388954,3750.164384,4175.178299,1942.181401,3638.743860,3796.485000,2358.296076,827.702641
30,2020-08,1893.728507,2109.017964,6430.340909,15523.882619,2067.651934,3383.231602,4179.002398,4173.404968,2242.749465,3974.185268,3949.114754,2277.768707,1043.213974
31,2020-09,1885.797183,2332.708333,6452.509642,13088.791878,2386.183575,3696.538071,4433.137525,4358.200000,3104.406528,4828.713043,4081.357724,2502.973941,1338.994012
32,2020-10,1396.321379,1427.617555,6355.282192,12518.551461,1467.186147,3789.480670,4375.252181,4377.491591,2766.011158,4959.080371,4059.404925,2451.282895,868.069322
33,2020-11,1222.905162,1306.328767,6336.713933,11985.148064,1280.369650,3811.449883,3593.266793,4289.983711,2124.913094,5112.692525,3979.032178,2315.354701,811.817722
34,2020-12,1309.438721,1481.750000,6466.153310,12077.611486,1520.070621,3784.623489,3543.698324,4335.279690,1986.244482,5497.387097,4031.672222,2344.226293,894.060669
35,2021-01,1686.192412,2196.741573,6847.594315,11689.899497,2251.090047,4270.259358,3613.183448,4900.551768,2130.619289,5193.103030,3941.878116,2567.817590,1093.787097
36,2021-02,1620.468665,2464.511364,6926.620879,11640.642487,2442.592784,4818.730303,3982.017094,5850.609375,1950.841558,5399.755627,4025.428977,2699.167300,1140.874150
37,2021-03,1357.283465,2091.705202,6775.527704,11540.504975,2026.931818,4831.392971,4150.058091,5868.570707,1651.913924,5081.564024,4112.700000,2669.633117,956.475460
38,2021-04,1266.906582,1740.074074,6730.225263,12140.528455,1491.690647,4366.299320,4250.466073,5755.404517,1589.053061,4560.220049,4184.008850,2701.760989,780.921114
39,2021-05,1243.648148,1465.433526,6600.251309,12711.171355,1275.458515,3525.792105,4060.066207,6006.839286,1591.135550,4350.234783,4001.188202,2715.626667,702.954416
40,2021-06,1415.518421,1449.971591,6588.248663,13200.343915,1536.607143,3309.693506,3914.286920,6245.876802,1615.331633,3873.360465,4043.650146,2648.774194,699.544160
41,2021-07,1580.465169,1220.911215,6756.880795,13339.585746,1208.161765,3207.174468,3888.231127,6318.700965,1734.207188,3850.423267,4038.430233,2601.726776,780.405213
42,2021-08,1842.160112,1450.315789,6847.425197,14655.340369,1467.386364,3305.164557,4297.972261,6246.528205,1995.099256,3920.294118,4025.472973,2323.107937,930.917355
43,2021-09,1956.367206,1942.868421,6965.845011,16955.444685,1933.248062,3538.517312,4357.281116,5984.234086,1934.100604,4218.851626,4151.889610,2321.194915,1020.637860
44,2021-10,1705.481894,1678.581006,7071.000000,16673.056300,1624.363208,3558.568123,3947.480845,5597.773316,1796.007634,4295.307292,4025.676796,2176.522667,954.462338
45,2021-11,1504.458101,1983.208791,7075.839779,16304.598901,1889.851485,3472.802111,3886.297959,5485.084100,1871.601562,4367.189944,4175.381089,2246.056150,1131.577540
46,2021-12,1373.174688,1918.156584,6908.007220,16203.333333,1978.591549,3410.564912,3971.000000,5487.073192,1937.305944,4737.916988,4094.895372,2103.982578,1232.249567
47,2022-01,1369.454545,2266.783920,7151.819672,2940.952736,2360.233161,3470.690722,4053.891582,5876.808576,1754.109415,4938.885154,4156.785100,2365.982188,1206.768229
48,2022-02,1364.817722,2129.500000,7282.396783,2740.278195,2178.936782,3415.852243,3986.769131,5997.669903,1708.022901,4118.920213,4221.213450,2330.163265,1124.749333
49,2022-03,1242.253112,1852.822642,7379.959091,2719.486653,1883.224299,3235.433476,4006.547009,6116.832669,1621.911157,4368.547210,4199.210900,2233.008316,1013.803419
50,2022-04,1237.225316,1505.218605,7541.667622,2773.762500,1508.453039,3226.130548,4168.795630,6081.244337,1624.639098,4662.639037,4265.495627,2226.826972,819.501299
51,2022-05,1180.804569,1278.632287,7532.828909,3267.980000,1296.235955,3242.751295,4224.461837,6308.200331,1780.882793,4611.753316,4347.946429,2292.424936,709.868557
52,2022-06,1288.768763,1408.794224,7565.589450,3416.199203,1434.557522,3567.212245,4153.591710,6440.105960,1971.672032,4321.057082,4363.676815,2339.525458,741.249493
53,2022-07,2100.477778,1822.224771,7780.861272,3370.838710,1817.660819,3954.868354,4402.551192,6373.612040,2273.969309,3870.669377,4244.300283,2423.718346,1166.837398
54,2022-08,2012.232955,1947.871287,7715.393393,3255.239186,1974.750000,3951.591512,4496.964942,6237.728055,2502.560224,4032.461756,4275.943953,2372.021108,1264.813889
55,2022-09,1846.237875,2142.605932,7614.114286,3233.356557,2105.980392,4081.203463,4543.223373,6309.159544,2799.515625,4512.820046,4376.766509,2394.036957,1219.305677
56,2022-10,1335.667526,1691.711712,7503.103858,3337.428212,1612.628571,4113.407895,4232.479042,6300.455185,2846.245902,4926.037901,4343.302053,2201.940722,1034.388601
57,2022-11,1197.565789,1439.616438,7633.168142,3127.061381,1430.436047,4144.168000,3519.706199,6443.929220,2418.190476,4654.052632,4505.866667,2221.931034,865.916230
58,2022-12,1109.304569,1314.454545,7755.818182,3045.575000,1338.333333,4205.324607,3241.105670,6465.921986,2078.051813,4739.843137,4624.588235,2257.235897,937.846154

In [ ]:
prot = ["닭고기", "돼지고기", "달걀"]
fish = ["고등어", "오징어"]
vege = ["상추", "호박", "애호박", "양파", "무", "오이"]
frut = ["사과", "배"]

In [ ]:
df_score.columns

Index([     '소비자물가지수(단일)',     '총지수 (신선식품지수)',    '신선식품 (신선식품지수)',
          '신선어개 (신선식품지수)',    '신선채소 (신선식품지수)',    '신선과실 (신선식품지수)',
        '신선식품제외 (신선식품지수)',     '총지수 (수입물가지수)',      '과일 (수입물가지수)',
          '냉동채소 (수입물가지수)',     '쇠고기 (수입물가지수)',    '돼지고기 (수입물가지수)',
           '닭고기 (수입물가지수)',   '신선수산물 (수입물가지수)',   '냉동수산물 (수입물가지수)',
         '총지수 (품목별소비자물가)',    '배추 (품목별소비자물가)',    '상추 (품목별소비자물가)',
          '오이 (품목별소비자물가)',    '호박 (품목별소비자물가)',    '양파 (품목별소비자물가)',
          '사과 (품목별소비자물가)',     '배 (품목별소비자물가)',  '돼지고기 (품목별소비자물가)',
         '닭고기 (품목별소비자물가)',    '달걀 (품목별소비자물가)',    '갈치 (품목별소비자물가)',
          '명태 (품목별소비자물가)',    '조기 (품목별소비자물가)',   '고등어 (품목별소비자물가)',
          '총지수 (생산자물가지수)',     '배추 (생산자물가지수)',     '상추 (생산자물가지수)',
           '오이 (생산자물가지수)',     '호박 (생산자물가지수)',     '양파 (생산자물가지수)',
           '사과 (생산자물가지수)',      '배 (생산자물가지수)',    '쇠고기 (생산자물가지수)',
         '돼지고기 (생산자물가지수)',    '닭고기 (생산자물가지수)',     '달걀 (생산자물가지수)',
           '조기 (생산자물가지수)',     '갈치 (생산자물가지수)',    '고등어 (생산자물가지수)',
         '기타어류 (생산자물가지수)',   '물오징어 (생산자물가지수)', 'Food Price Index',
                   'Meat',            'Dairy',          'Cereals',
                   'Oils',            'Sugar',           '생활물가지수',
                     '식품',            '식품 이외',              '전월세',
          '전·월세포함 생활물가지수',                nan],
      dtype='object', name='종목')

In [207]:
df_pig = df_score[["소비자물가지수(단일)", "신선식품 (신선식품지수)", "돼지고기 (수입물가지수)", "돼지고기 (품목별소비자물가)", "돼지고기 (생산자물가지수)", "Meat", "식품"]]
df_chicken = df_score[["소비자물가지수(단일)", "신선식품 (신선식품지수)", "닭고기 (수입물가지수)", "닭고기 (품목별소비자물가)", "닭고기 (생산자물가지수)", "Meat", "식품"]]
df_egg = df_score[["소비자물가지수(단일)", "신선식품 (신선식품지수)", "총지수 (수입물가지수)", "달걀 (품목별소비자물가)", "달걀 (생산자물가지수)", "Meat", "식품"]]

In [208]:
df_pig.corr(method='pearson')

종목,소비자물가지수(단일),신선식품 (신선식품지수),돼지고기 (수입물가지수),돼지고기 (품목별소비자물가),돼지고기 (생산자물가지수),Meat,식품
종목,,,,,,,
소비자물가지수(단일),1.000000,0.741969,0.725940,0.819099,0.733972,0.878134,0.241460
신선식품 (신선식품지수),0.741969,1.000000,0.574640,0.681615,0.552973,0.525061,0.503979
돼지고기 (수입물가지수),0.725940,0.574640,1.000000,0.714257,0.595841,0.820252,0.523219
돼지고기 (품목별소비자물가),0.819099,0.681615,0.714257,1.000000,0.898238,0.734359,0.417983
돼지고기 (생산자물가지수),0.733972,0.552973,0.595841,0.898238,1.000000,0.691474,0.297646
Meat,0.878134,0.525061,0.820252,0.734359,0.691474,1.000000,0.171012
식품,0.241460,0.503979,0.523219,0.417983,0.297646,0.171012,1.000000

In [209]:
df_pig = df_pig.drop("돼지고기 (품목별소비자물가)", axis=1)
df_pig.corr(method='pearson')

종목,소비자물가지수(단일),신선식품 (신선식품지수),돼지고기 (수입물가지수),돼지고기 (생산자물가지수),Meat,식품
종목,,,,,,
소비자물가지수(단일),1.000000,0.741969,0.725940,0.733972,0.878134,0.241460
신선식품 (신선식품지수),0.741969,1.000000,0.574640,0.552973,0.525061,0.503979
돼지고기 (수입물가지수),0.725940,0.574640,1.000000,0.595841,0.820252,0.523219
돼지고기 (생산자물가지수),0.733972,0.552973,0.595841,1.000000,0.691474,0.297646
Meat,0.878134,0.525061,0.820252,0.691474,1.000000,0.171012
식품,0.241460,0.503979,0.523219,0.297646,0.171012,1.000000

In [210]:
df_chicken.corr(method='pearson')

종목,소비자물가지수(단일),신선식품 (신선식품지수),닭고기 (수입물가지수),닭고기 (품목별소비자물가),닭고기 (생산자물가지수),Meat,식품
종목,,,,,,,
소비자물가지수(단일),1.000000,0.741969,0.743605,0.900267,0.936440,0.878134,0.241460
신선식품 (신선식품지수),0.741969,1.000000,0.328910,0.636909,0.700855,0.525061,0.503979
닭고기 (수입물가지수),0.743605,0.328910,1.000000,0.770247,0.661506,0.801556,-0.164576
닭고기 (품목별소비자물가),0.900267,0.636909,0.770247,1.000000,0.901371,0.759574,0.088828
닭고기 (생산자물가지수),0.936440,0.700855,0.661506,0.901371,1.000000,0.855904,0.259316
Meat,0.878134,0.525061,0.801556,0.759574,0.855904,1.000000,0.171012
식품,0.241460,0.503979,-0.164576,0.088828,0.259316,0.171012,1.000000

In [211]:
df_chicken = df_chicken.drop(["소비자물가지수(단일)", "닭고기 (생산자물가지수)"], axis=1)
df_chicken.corr(method='pearson')

종목,신선식품 (신선식품지수),닭고기 (수입물가지수),닭고기 (품목별소비자물가),Meat,식품
종목,,,,,
신선식품 (신선식품지수),1.000000,0.328910,0.636909,0.525061,0.503979
닭고기 (수입물가지수),0.328910,1.000000,0.770247,0.801556,-0.164576
닭고기 (품목별소비자물가),0.636909,0.770247,1.000000,0.759574,0.088828
Meat,0.525061,0.801556,0.759574,1.000000,0.171012
식품,0.503979,-0.164576,0.088828,0.171012,1.000000

In [212]:
df_egg.corr(method='pearson')

종목,소비자물가지수(단일),신선식품 (신선식품지수),총지수 (수입물가지수),달걀 (품목별소비자물가),달걀 (생산자물가지수),Meat,식품
종목,,,,,,,
소비자물가지수(단일),1.000000,0.741969,0.926556,0.771333,0.707699,0.878134,0.241460
신선식품 (신선식품지수),0.741969,1.000000,0.585322,0.708684,0.706107,0.525061,0.503979
총지수 (수입물가지수),0.926556,0.585322,1.000000,0.654825,0.569714,0.907402,0.020681
달걀 (품목별소비자물가),0.771333,0.708684,0.654825,1.000000,0.965703,0.787116,0.557226
달걀 (생산자물가지수),0.707699,0.706107,0.569714,0.965703,1.000000,0.719548,0.614591
Meat,0.878134,0.525061,0.907402,0.787116,0.719548,1.000000,0.171012
식품,0.241460,0.503979,0.020681,0.557226,0.614591,0.171012,1.000000

In [213]:
df_egg = df_egg.drop("총지수 (수입물가지수)", axis=1)
df_egg = df_egg.drop("달걀 (생산자물가지수)", axis=1)
df_egg.corr(method="pearson")

종목             소비자물가지수(단일)  신선식품 (신선식품지수)  달걀 (품목별소비자물가)      Meat        식품
종목
소비자물가지수(단일)       1.000000       0.741969       0.771333  0.878134  0.241460
신선식품 (신선식품지수)     0.741969       1.000000       0.708684  0.525061  0.503979
달걀 (품목별소비자물가)     0.771333       0.708684       1.000000  0.787116  0.557226
Meat              0.878134       0.525061       0.787116  1.000000  0.171012
식품                0.241460       0.503979       0.557226  0.171012  1.000000

In [214]:
df_pig.to_csv("돼지고기 지수.csv", encoding='cp949')
df_chicken.to_csv("닭고기 지수.csv", encoding='cp949')
df_egg.to_csv("달걀 지수.csv", encoding='cp949')

In [215]:
df_high = df_score[["소비자물가지수(단일)", "신선어개 (신선식품지수)", "신선수산물 (수입물가지수)", "고등어 (품목별소비자물가)", "고등어 (생산자물가지수)", "Food Price Index", "식품"]]
df_squid = df_score[["소비자물가지수(단일)", "신선어개 (신선식품지수)", "신선수산물 (수입물가지수)", "총지수 (품목별소비자물가)", "기타어류 (생산자물가지수)", "Food Price Index", "식품"]]

In [216]:
df_high.corr(method='pearson')

종목,소비자물가지수(단일),신선어개 (신선식품지수),신선수산물 (수입물가지수),고등어 (품목별소비자물가),고등어 (생산자물가지수),Food Price Index,식품
종목,,,,,,,
소비자물가지수(단일),1.000000,0.813114,0.352819,0.781885,0.667718,0.893869,0.241460
신선어개 (신선식품지수),0.813114,1.000000,0.264148,0.934478,0.924891,0.782441,0.431702
신선수산물 (수입물가지수),0.352819,0.264148,1.000000,0.314017,0.318320,0.209794,-0.172289
고등어 (품목별소비자물가),0.781885,0.934478,0.314017,1.000000,0.949288,0.803403,0.418750
고등어 (생산자물가지수),0.667718,0.924891,0.318320,0.949288,1.000000,0.700928,0.410688
Food Price Index,0.893869,0.782441,0.209794,0.803403,0.700928,1.000000,0.252816
식품,0.241460,0.431702,-0.172289,0.418750,0.410688,0.252816,1.000000

In [217]:
df_high = df_high.drop(["고등어 (품목별소비자물가)", "신선어개 (신선식품지수)"], axis=1)
df_high.corr(method='pearson')

종목,소비자물가지수(단일),신선수산물 (수입물가지수),고등어 (생산자물가지수),Food Price Index,식품
종목,,,,,
소비자물가지수(단일),1.000000,0.352819,0.667718,0.893869,0.241460
신선수산물 (수입물가지수),0.352819,1.000000,0.318320,0.209794,-0.172289
고등어 (생산자물가지수),0.667718,0.318320,1.000000,0.700928,0.410688
Food Price Index,0.893869,0.209794,0.700928,1.000000,0.252816
식품,0.241460,-0.172289,0.410688,0.252816,1.000000

In [218]:
df_squid.corr(method='pearson')

종목,소비자물가지수(단일),신선어개 (신선식품지수),신선수산물 (수입물가지수),총지수 (품목별소비자물가),기타어류 (생산자물가지수),Food Price Index,식품
종목,,,,,,,
소비자물가지수(단일),1.000000,0.813114,0.352819,1.000000,0.411965,0.893869,0.241460
신선어개 (신선식품지수),0.813114,1.000000,0.264148,0.813114,0.379411,0.782441,0.431702
신선수산물 (수입물가지수),0.352819,0.264148,1.000000,0.352819,0.554220,0.209794,-0.172289
총지수 (품목별소비자물가),1.000000,0.813114,0.352819,1.000000,0.411965,0.893869,0.241460
기타어류 (생산자물가지수),0.411965,0.379411,0.554220,0.411965,1.000000,0.251644,0.075202
Food Price Index,0.893869,0.782441,0.209794,0.893869,0.251644,1.000000,0.252816
식품,0.241460,0.431702,-0.172289,0.241460,0.075202,0.252816,1.000000

In [219]:
df_squid = df_squid.drop("소비자물가지수(단일)", axis=1)

In [220]:
df_squid.corr(method='pearson')

종목,신선어개 (신선식품지수),신선수산물 (수입물가지수),총지수 (품목별소비자물가),기타어류 (생산자물가지수),Food Price Index,식품
종목,,,,,,
신선어개 (신선식품지수),1.000000,0.264148,0.813114,0.379411,0.782441,0.431702
신선수산물 (수입물가지수),0.264148,1.000000,0.352819,0.554220,0.209794,-0.172289
총지수 (품목별소비자물가),0.813114,0.352819,1.000000,0.411965,0.893869,0.241460
기타어류 (생산자물가지수),0.379411,0.554220,0.411965,1.000000,0.251644,0.075202
Food Price Index,0.782441,0.209794,0.893869,0.251644,1.000000,0.252816
식품,0.431702,-0.172289,0.241460,0.075202,0.252816,1.000000

In [221]:
df_squid = df_squid.drop("총지수 (품목별소비자물가)", axis=1)

In [222]:
df_high.to_csv("고등어 지수.csv", encoding='cp949')
df_squid.to_csv("오징어 지수.csv", encoding='cp949')

In [223]:
df_sangcu = df_score[["소비자물가지수(단일)", "신선채소 (신선식품지수)", "냉동채소 (수입물가지수)", "상추 (품목별소비자물가)", "상추 (생산자물가지수)", "Food Price Index", "식품"]]
df_pumkin = df_score[["소비자물가지수(단일)", "신선채소 (신선식품지수)", "냉동채소 (수입물가지수)", "호박 (품목별소비자물가)", "호박 (생산자물가지수)", "Food Price Index", "식품"]]
df_onion = df_score[["소비자물가지수(단일)", "신선채소 (신선식품지수)", "냉동채소 (수입물가지수)", "양파 (품목별소비자물가)", "양파 (생산자물가지수)", "Food Price Index", "식품"]]
df_raddish = df_score[["소비자물가지수(단일)", "신선채소 (신선식품지수)", "냉동채소 (수입물가지수)", "총지수 (품목별소비자물가)", "총지수 (생산자물가지수)", "Food Price Index", "식품"]]
df_cucumber = df_score[["소비자물가지수(단일)", "신선채소 (신선식품지수)", "냉동채소 (수입물가지수)", "오이 (품목별소비자물가)", "오이 (생산자물가지수)", "Food Price Index", "식품"]]

In [224]:
df_sangcu = df_sangcu.drop("소비자물가지수(단일)", axis=1)
df_sangcu.corr(method='pearson')

종목,신선채소 (신선식품지수),냉동채소 (수입물가지수),상추 (품목별소비자물가),상추 (생산자물가지수),Food Price Index,식품
종목,,,,,,
신선채소 (신선식품지수),1.000000,0.487306,0.676145,0.465937,0.451171,0.525985
냉동채소 (수입물가지수),0.487306,1.000000,0.335335,0.251341,0.831060,0.204273
상추 (품목별소비자물가),0.676145,0.335335,1.000000,0.917767,0.226849,0.475998
상추 (생산자물가지수),0.465937,0.251341,0.917767,1.000000,0.176130,0.374651
Food Price Index,0.451171,0.831060,0.226849,0.176130,1.000000,0.252816
식품,0.525985,0.204273,0.475998,0.374651,0.252816,1.000000

In [225]:
df_pumkin = df_pumkin.drop("소비자물가지수(단일)", axis=1)
df_pumkin.corr(method='pearson')

종목,신선채소 (신선식품지수),냉동채소 (수입물가지수),호박 (품목별소비자물가),호박 (생산자물가지수),Food Price Index,식품
종목,,,,,,
신선채소 (신선식품지수),1.000000,0.487306,0.722967,0.643403,0.451171,0.525985
냉동채소 (수입물가지수),0.487306,1.000000,0.275391,0.271443,0.831060,0.204273
호박 (품목별소비자물가),0.722967,0.275391,1.000000,0.890143,0.231113,0.221404
호박 (생산자물가지수),0.643403,0.271443,0.890143,1.000000,0.237202,0.242115
Food Price Index,0.451171,0.831060,0.231113,0.237202,1.000000,0.252816
식품,0.525985,0.204273,0.221404,0.242115,0.252816,1.000000

In [226]:
df_onion = df_onion.drop("소비자물가지수(단일)", axis=1)
df_onion.corr(method='pearson')

종목,신선채소 (신선식품지수),냉동채소 (수입물가지수),양파 (품목별소비자물가),양파 (생산자물가지수),Food Price Index,식품
종목,,,,,,
신선채소 (신선식품지수),1.000000,0.487306,0.460887,0.597421,0.451171,0.525985
냉동채소 (수입물가지수),0.487306,1.000000,0.195083,0.361482,0.831060,0.204273
양파 (품목별소비자물가),0.460887,0.195083,1.000000,0.885572,0.230906,0.487815
양파 (생산자물가지수),0.597421,0.361482,0.885572,1.000000,0.329030,0.519968
Food Price Index,0.451171,0.831060,0.230906,0.329030,1.000000,0.252816
식품,0.525985,0.204273,0.487815,0.519968,0.252816,1.000000

In [227]:
df_raddish = df_raddish.drop("총지수 (생산자물가지수)", axis=1)
df_raddish.corr(method='pearson')

종목,소비자물가지수(단일),신선채소 (신선식품지수),냉동채소 (수입물가지수),총지수 (품목별소비자물가),Food Price Index,식품
종목,,,,,,
소비자물가지수(단일),1.000000,0.547355,0.935747,1.000000,0.893869,0.241460
신선채소 (신선식품지수),0.547355,1.000000,0.487306,0.547355,0.451171,0.525985
냉동채소 (수입물가지수),0.935747,0.487306,1.000000,0.935747,0.831060,0.204273
총지수 (품목별소비자물가),1.000000,0.547355,0.935747,1.000000,0.893869,0.241460
Food Price Index,0.893869,0.451171,0.831060,0.893869,1.000000,0.252816
식품,0.241460,0.525985,0.204273,0.241460,0.252816,1.000000

In [228]:
df_cucumber = df_cucumber.drop("소비자물가지수(단일)", axis=1)
df_cucumber.corr(method='pearson')

종목,신선채소 (신선식품지수),냉동채소 (수입물가지수),오이 (품목별소비자물가),오이 (생산자물가지수),Food Price Index,식품
종목,,,,,,
신선채소 (신선식품지수),1.000000,0.487306,0.665365,0.552678,0.451171,0.525985
냉동채소 (수입물가지수),0.487306,1.000000,0.477479,0.394043,0.831060,0.204273
오이 (품목별소비자물가),0.665365,0.477479,1.000000,0.865276,0.414856,0.153130
오이 (생산자물가지수),0.552678,0.394043,0.865276,1.000000,0.299700,0.171085
Food Price Index,0.451171,0.831060,0.414856,0.299700,1.000000,0.252816
식품,0.525985,0.204273,0.153130,0.171085,0.252816,1.000000

In [229]:
df_sangcu.to_csv("상추 지수.csv", encoding='cp949')
df_pumkin.to_csv("호박 지수.csv", encoding='cp949')
df_onion.to_csv("양파 지수.csv", encoding='cp949')
df_raddish.to_csv("무 지수.csv", encoding='cp949')
df_cucumber.to_csv("오이 지수.csv", encoding='cp949')

In [230]:
df_apple = df_score[["소비자물가지수(단일)", "신선식품 (신선식품지수)", "과일 (수입물가지수)", "사과 (품목별소비자물가)", "사과 (생산자물가지수)", "Food Price Index", "식품"]]
df_pear = df_score[["소비자물가지수(단일)", "신선식품 (신선식품지수)", "과일 (수입물가지수)", "배 (품목별소비자물가)", "배 (생산자물가지수)", "Food Price Index", "식품"]]

In [231]:
df_apple = df_apple.drop("소비자물가지수(단일)", axis=1)
df_apple.corr(method='pearson')

종목,신선식품 (신선식품지수),과일 (수입물가지수),사과 (품목별소비자물가),사과 (생산자물가지수),Food Price Index,식품
종목,,,,,,
신선식품 (신선식품지수),1.000000,0.505794,0.615103,0.476131,0.691257,0.503979
과일 (수입물가지수),0.505794,1.000000,0.006098,0.010145,0.673861,0.080333
사과 (품목별소비자물가),0.615103,0.006098,1.000000,0.745999,0.340146,0.646649
사과 (생산자물가지수),0.476131,0.010145,0.745999,1.000000,0.181691,0.514687
Food Price Index,0.691257,0.673861,0.340146,0.181691,1.000000,0.252816
식품,0.503979,0.080333,0.646649,0.514687,0.252816,1.000000

In [232]:
df_pear = df_pear.drop("소비자물가지수(단일)", axis=1)
df_pear.corr(method='pearson')

종목,신선식품 (신선식품지수),과일 (수입물가지수),배 (품목별소비자물가),배 (생산자물가지수),Food Price Index,식품
종목,,,,,,
신선식품 (신선식품지수),1.000000,0.505794,0.551852,0.251199,0.691257,0.503979
과일 (수입물가지수),0.505794,1.000000,0.202385,0.006600,0.673861,0.080333
배 (품목별소비자물가),0.551852,0.202385,1.000000,0.769451,0.592851,0.618692
배 (생산자물가지수),0.251199,0.006600,0.769451,1.000000,0.288685,0.485647
Food Price Index,0.691257,0.673861,0.592851,0.288685,1.000000,0.252816
식품,0.503979,0.080333,0.618692,0.485647,0.252816,1.000000

In [233]:
df_apple.to_csv("사과 지수.csv", encoding='cp949')
df_pear.to_csv("배 지수.csv", encoding='cp949')

#### 2020-03 결측

In [ ]:
ss = [1199.5749745025016,
 1556.0556395484746,
 6317.205148691031,
 13333.676839272382,
 1633.6678718893884,
 3255.9709344440816,
 3640.4739741900303,
 4173.901293561932,
 2168.3388885718164,
 4417.404937122942,
 3953.689291833378,
 1915.458860873051,
 886.6134301741374]

In [ ]:
df_given = df_given.set_index("년도-월")
df_given

,상추,호박,닭고기,돼지고기,애호박,양파,배,달걀,무,오징어,고등어,사과,오이
년도-월,,,,,,,,,,,,,
2018-01,1336.262626,2068.648649,5942.083333,12790.315789,2222.377049,3562.474747,2899.890000,4252.005102,1716.200000,3998.865979,3842.258065,1813.230000,991.630000
2018-02,1141.217822,2024.594595,6079.690722,13177.525773,2044.193548,3462.000000,3321.143564,4214.560606,2454.808081,3808.091837,3696.774194,1968.178218,824.090000
2018-03,1006.111111,2036.951220,6135.204082,13084.432990,2033.333333,3232.161616,3256.914573,3745.994949,2498.865979,3803.552083,3969.326087,1802.787879,724.383838
2018-04,942.686869,1393.170732,6072.572917,13087.368421,1386.525424,3182.787879,3309.874372,3708.994898,2653.084211,3934.795918,3379.795455,1825.581633,588.320000
2018-05,957.470000,1579.268293,6102.693878,13626.104167,1573.135593,2995.440000,2863.055276,3615.611111,2410.752577,3746.010101,3398.426966,1843.191919,633.131313
2018-06,850.710000,1095.000000,5977.326316,14135.063830,1083.965517,2901.606061,2772.365000,3446.373737,1934.226804,3698.835052,3512.954545,1870.393939,535.585859
2018-07,1085.494949,1074.634146,6144.896907,14957.543478,949.824561,2921.696970,3700.489899,3598.865979,2385.104167,3898.175258,3251.838710,1808.591837,674.373737
2018-08,1653.156250,1749.285714,6502.734043,14859.782609,1786.666667,2971.848485,3896.858065,3962.229592,3102.535211,4173.568421,3423.219780,1944.680412,1002.412371
2018-09,1812.855670,1602.272727,6315.869565,14370.978261,1555.754717,2983.160000,4062.946809,4107.076142,3008.888889,3911.041237,3318.648352,2294.877551,834.757576
2018-10,1061.180000,1349.204545,6437.135417,13724.893617,1306.842105,2867.099010,3109.641791,4043.560606,2006.229167,4393.978495,3212.769231,1943.178218,699.820000
2018-11,946.870000,1563.977273,6265.635417,12529.375000,1507.363636,2873.980000,2767.653061,3976.274112,1659.696970,4582.625000,3128.107527,1759.224490,766.989796
2018-12,975.530000,1622.558140,6353.191489,13371.875000,1705.535714,2865.150000,2956.234694,3957.326531,1617.474747,4425.651163,3420.414894,1871.181818,868.570000
2019-01,967.039604,1833.720930,6584.840426,13030.000000,1816.491228,2771.168317,3043.383838,3831.517588,1494.300000,4174.638298,3149.021505,2056.092784,936.163265
2019-02,890.535354,1482.325581,6483.462366,12797.263158,1466.839286,2695.080000,2914.566327,3637.949239,1407.500000,4060.602151,3258.645161,1967.319588,817.775510
2019-03,917.430000,1414.431818,6360.688172,12531.041667,1339.821429,2684.727273,2847.954315,3716.801020,1360.800000,4138.333333,3400.924731,1921.463918,762.597938
2019-04,918.010221,1235.944882,6300.909091,13175.090265,1144.870482,2983.257679,2821.331029,3903.808862,1408.430034,3965.772809,3477.387640,1930.981067,617.512069
2019-05,1018.953654,1187.306202,6311.875236,13353.109462,1064.277228,3018.471530,2868.844424,3921.741818,1494.003559,3733.723949,3451.812133,1923.488414,570.566071
2019-06,961.842881,1242.602996,6214.675347,13278.640275,1169.299419,2757.945902,3066.440397,3885.003336,1542.124386,3619.875630,3581.085561,1956.318555,524.008278
2019-07,1045.984330,1139.996904,6220.574213,13166.475483,1062.962865,2462.071225,3357.534247,3876.664493,1543.315264,3353.939655,3596.872611,1987.079886,637.878917
2019-08,1585.289683,1563.318841,6294.580601,13035.023192,1646.343284,2513.428758,3609.969516,3841.207171,1606.509804,3732.232713,3411.187151,1895.336898,960.015957
2019-09,1441.651515,1576.179941,6293.083451,13796.867816,1595.864450,2542.970109,3814.836573,3965.729339,1812.404891,4020.532148,3486.908962,1951.994467,891.359504
2019-10,1617.694581,1416.203753,6465.061460,13466.053165,1377.234375,2493.795371,4133.514865,4068.869188,2419.953260,3968.268991,3523.632783,1679.641626,841.843016
2019-11,1302.853470,1335.486188,6364.308525,12663.823454,1225.710956,2555.246523,3552.893299,4139.268214,2498.761290,3845.329700,3620.263434,1681.329923,881.584184
2019-12,1230.754765,1405.358333,6350.912467,13013.253807,1372.246014,2674.160200,3528.719343,4207.525543,2570.766355,4215.686192,3798.647849,1734.859296,955.549937
2020-01,1371.578674,1888.323615,6342.450954,12735.434501,2021.421801,2871.819462,3669.584042,4178.520915,2767.722689,4779.320109,4017.116959,1950.795839,1167.951886
2020-02,1437.681319,2018.125000,6379.611765,12440.725275,2152.800000,2944.054945,3709.491803,4106.407821,2579.090909,4584.977273,3974.939024,1843.417582,1154.842697
2020-04,1002.970414,1206.150327,6275.269716,13424.348281,1245.148148,3624.234586,3515.377513,4214.271982,1699.897661,4171.506667,3811.107492,1884.237537,654.452416
2020-05,986.069492,1111.623616,6271.488160,14734.199301,1115.301538,3583.774744,3667.442539,4196.404456,1626.644295,4133.815700,4011.593692,1983.384486,569.206723
2020-06,1076.932785,1186.334254,6301.843658,15644.893010,1220.305040,3481.795014,3620.216851,4190.838977,1717.577808,3350.962759,3977.505443,2181.407407,616.054201
2020-07,1376.885514,1314.289100,6397.299625,15178.641371,1352.500000,3252.388954,3750.164384,4175.178299,1942.181401,3638.743860,3796.485000,2358.296076,827.702641
2020-08,1893.728507,2109.017964,6430.340909,15523.882619,2067.651934,3383.231602,4179.002398,4173.404968,2242.749465,3974.185268,3949.114754,2277.768707,1043.213974
2020-09,1885.797183,2332.708333,6452.509642,13088.791878,2386.183575,3696.538071,4433.137525,4358.200000,3104.406528,4828.713043,4081.357724,2502.973941,1338.994012
2020-10,1396.321379,1427.617555,6355.282192,12518.551461,1467.186147,3789.480670,4375.252181,4377.491591,2766.011158,4959.080371,4059.404925,2451.282895,868.069322
2020-11,1222.905162,1306.328767,6336.713933,11985.148064,1280.369650,3811.449883,3593.266793,4289.983711,2124.913094,5112.692525,3979.032178,2315.354701,811.817722
2020-12,1309.438721,1481.750000,6466.153310,12077.611486,1520.070621,3784.623489,3543.698324,4335.279690,1986.244482,5497.387097,4031.672222,2344.226293,894.060669
2021-01,1686.192412,2196.741573,6847.594315,11689.899497,2251.090047,4270.259358,3613.183448,4900.551768,2130.619289,5193.103030,3941.878116,2567.817590,1093.787097
2021-02,1620.468665,2464.511364,6926.620879,11640.642487,2442.592784,4818.730303,3982.017094,5850.609375,1950.841558,5399.755627,4025.428977,2699.167300,1140.874150
2021-03,1357.283465,2091.705202,6775.527704,11540.504975,2026.931818,4831.392971,4150.058091,5868.570707,1651.913924,5081.564024,4112.700000,2669.633117,956.475460
2021-04,1266.906582,1740.074074,6730.225263,12140.528455,1491.690647,4366.299320,4250.466073,5755.404517,1589.053061,4560.220049,4184.008850,2701.760989,780.921114
2021-05,1243.648148,1465.433526,6600.251309,12711.171355,1275.458515,3525.792105,4060.066207,6006.839286,1591.135550,4350.234783,4001.188202,2715.626667,702.954416
2021-06,1415.518421,1449.971591,6588.248663,13200.343915,1536.607143,3309.693506,3914.286920,6245.876802,1615.331633,3873.360465,4043.650146,2648.774194,699.544160
2021-07,1580.465169,1220.911215,6756.880795,13339.585746,1208.161765,3207.174468,3888.231127,6318.700965,1734.207188,3850.423267,4038.430233,2601.726776,780.405213
2021-08,1842.160112,1450.315789,6847.425197,14655.340369,1467.386364,3305.164557,4297.972261,6246.528205,1995.099256,3920.294118,4025.472973,2323.107937,930.917355
2021-09,1956.367206,1942.868421,6965.845011,16955.444685,1933.248062,3538.517312,4357.281116,5984.234086,1934.100604,4218.851626,4151.889610,2321.194915,1020.637860
2021-10,1705.481894,1678.581006,7071.000000,16673.056300,1624.363208,3558.568123,3947.480845,5597.773316,1796.007634,4295.307292,4025.676796,2176.522667,954.462338
2021-11,1504.458101,1983.208791,7075.839779,16304.598901,1889.851485,3472.802111,3886.297959,5485.084100,1871.601562,4367.189944,4175.381089,2246.056150,1131.577540
2021-12,1373.174688,1918.156584,6908.007220,16203.333333,1978.591549,3410.564912,3971.000000,5487.073192,1937.305944,4737.916988,4094.895372,2103.982578,1232.249567
2022-01,1369.454545,2266.783920,7151.819672,2940.952736,2360.233161,3470.690722,4053.891582,5876.808576,1754.109415,4938.885154,4156.785100,2365.982188,1206.768229
2022-02,1364.817722,2129.500000,7282.396783,2740.278195,2178.936782,3415.852243,3986.769131,5997.669903,1708.022901,4118.920213,4221.213450,2330.163265,1124.749333
2022-03,1242.253112,1852.822642,7379.959091,2719.486653,1883.224299,3235.433476,4006.547009,6116.832669,1621.911157,4368.547210,4199.210900,2233.008316,1013.803419
2022-04,1237.225316,1505.218605,7541.667622,2773.762500,1508.453039,3226.130548,4168.795630,6081.244337,1624.639098,4662.639037,4265.495627,2226.826972,819.501299
2022-05,1180.804569,1278.632287,7532.828909,3267.980000,1296.235955,3242.751295,4224.461837,6308.200331,1780.882793,4611.753316,4347.946429,2292.424936,709.868557
2022-06,1288.768763,1408.794224,7565.589450,3416.199203,1434.557522,3567.212245,4153.591710,6440.105960,1971.672032,4321.057082,4363.676815,2339.525458,741.249493
2022-07,2100.477778,1822.224771,7780.861272,3370.838710,1817.660819,3954.868354,4402.551192,6373.612040,2273.969309,3870.669377,4244.300283,2423.718346,1166.837398
2022-08,2012.232955,1947.871287,7715.393393,3255.239186,1974.750000,3951.591512,4496.964942,6237.728055,2502.560224,4032.461756,4275.943953,2372.021108,1264.813889
2022-09,1846.237875,2142.605932,7614.114286,3233.356557,2105.980392,4081.203463,4543.223373,6309.159544,2799.515625,4512.820046,4376.766509,2394.036957,1219.305677
2022-10,1335.667526,1691.711712,7503.103858,3337.428212,1612.628571,4113.407895,4232.479042,6300.455185,2846.245902,4926.037901,4343.302053,2201.940722,1034.388601
2022-11,1197.565789,1439.616438,7633.168142,3127.061381,1430.436047,4144.168000,3519.706199,6443.929220,2418.190476,4654.052632,4505.866667,2221.931034,865.916230
2022-12,1109.304569,1314.454545,7755.818182,3045.575000,1338.333333,4205.324607,3241.105670,6465.921986,2078.051813,4739.843137,4624.588235,2257.235897,937.846154

In [ ]:
df_test = df_given.transpose()

In [ ]:
df_test["2020-03"] = ss
df_test

년도-월,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,...,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2020-03
상추,1336.262626,1141.217822,1006.111111,942.686869,957.470000,850.710000,1085.494949,1653.156250,1812.855670,1061.180000,...,1237.225316,1180.804569,1288.768763,2100.477778,2012.232955,1846.237875,1335.667526,1197.565789,1109.304569,1199.574975
호박,2068.648649,2024.594595,2036.951220,1393.170732,1579.268293,1095.000000,1074.634146,1749.285714,1602.272727,1349.204545,...,1505.218605,1278.632287,1408.794224,1822.224771,1947.871287,2142.605932,1691.711712,1439.616438,1314.454545,1556.055640
닭고기,5942.083333,6079.690722,6135.204082,6072.572917,6102.693878,5977.326316,6144.896907,6502.734043,6315.869565,6437.135417,...,7541.667622,7532.828909,7565.589450,7780.861272,7715.393393,7614.114286,7503.103858,7633.168142,7755.818182,6317.205149
돼지고기,12790.315789,13177.525773,13084.432990,13087.368421,13626.104167,14135.063830,14957.543478,14859.782609,14370.978261,13724.893617,...,2773.762500,3267.980000,3416.199203,3370.838710,3255.239186,3233.356557,3337.428212,3127.061381,3045.575000,13333.676839
애호박,2222.377049,2044.193548,2033.333333,1386.525424,1573.135593,1083.965517,949.824561,1786.666667,1555.754717,1306.842105,...,1508.453039,1296.235955,1434.557522,1817.660819,1974.750000,2105.980392,1612.628571,1430.436047,1338.333333,1633.667872
양파,3562.474747,3462.000000,3232.161616,3182.787879,2995.440000,2901.606061,2921.696970,2971.848485,2983.160000,2867.099010,...,3226.130548,3242.751295,3567.212245,3954.868354,3951.591512,4081.203463,4113.407895,4144.168000,4205.324607,3255.970934
배,2899.890000,3321.143564,3256.914573,3309.874372,2863.055276,2772.365000,3700.489899,3896.858065,4062.946809,3109.641791,...,4168.795630,4224.461837,4153.591710,4402.551192,4496.964942,4543.223373,4232.479042,3519.706199,3241.105670,3640.473974
달걀,4252.005102,4214.560606,3745.994949,3708.994898,3615.611111,3446.373737,3598.865979,3962.229592,4107.076142,4043.560606,...,6081.244337,6308.200331,6440.105960,6373.612040,6237.728055,6309.159544,6300.455185,6443.929220,6465.921986,4173.901294
무,1716.200000,2454.808081,2498.865979,2653.084211,2410.752577,1934.226804,2385.104167,3102.535211,3008.888889,2006.229167,...,1624.639098,1780.882793,1971.672032,2273.969309,2502.560224,2799.515625,2846.245902,2418.190476,2078.051813,2168.338889
오징어,3998.865979,3808.091837,3803.552083,3934.795918,3746.010101,3698.835052,3898.175258,4173.568421,3911.041237,4393.978495,...,4662.639037,4611.753316,4321.057082,3870.669377,4032.461756,4512.820046,4926.037901,4654.052632,4739.843137,4417.404937
고등어,3842.258065,3696.774194,3969.326087,3379.795455,3398.426966,3512.954545,3251.838710,3423.219780,3318.648352,3212.769231,...,4265.495627,4347.946429,4363.676815,4244.300283,4275.943953,4376.766509,4343.302053,4505.866667,4624.588235,3953.689292
사과,1813.230000,1968.178218,1802.787879,1825.581633,1843.191919,1870.393939,1808.591837,1944.680412,2294.877551,1943.178218,...,2226.826972,2292.424936,2339.525458,2423.718346,2372.021108,2394.036957,2201.940722,2221.931034,2257.235897,1915.458861
오이,991.630000,824.090000,724.383838,588.320000,633.131313,535.585859,674.373737,1002.412371,834.757576,699.820000,...,819.501299,709.868557,741.249493,1166.837398,1264.813889,1219.305677,1034.388601,865.916230,937.846154,886.613430

In [ ]:
df_test.columns

Index(['2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06',
       '2018-07', '2018-08', '2018-09', '2018-10', '2018-11', '2018-12',
       '2019-01', '2019-02', '2019-03', '2019-04', '2019-05', '2019-06',
       '2019-07', '2019-08', '2019-09', '2019-10', '2019-11', '2019-12',
       '2020-01', '2020-02', '2020-04', '2020-05', '2020-06', '2020-07',
       '2020-08', '2020-09', '2020-10', '2020-11', '2020-12', '2021-01',
       '2021-02', '2021-03', '2021-04', '2021-05', '2021-06', '2021-07',
       '2021-08', '2021-09', '2021-10', '2021-11', '2021-12', '2022-01',
       '2022-02', '2022-03', '2022-04', '2022-05', '2022-06', '2022-07',
       '2022-08', '2022-09', '2022-10', '2022-11', '2022-12', '2020-03'],
      dtype='object', name='년도-월')

In [ ]:
new_columns = ['2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06',
       '2018-07', '2018-08', '2018-09', '2018-10', '2018-11', '2018-12',
       '2019-01', '2019-02', '2019-03', '2019-04', '2019-05', '2019-06',
       '2019-07', '2019-08', '2019-09', '2019-10', '2019-11', '2019-12',
       '2020-01', '2020-02', '2020-03', '2020-04', '2020-05', '2020-06', '2020-07',
       '2020-08', '2020-09', '2020-10', '2020-11', '2020-12', '2021-01',
       '2021-02', '2021-03', '2021-04', '2021-05', '2021-06', '2021-07',
       '2021-08', '2021-09', '2021-10', '2021-11', '2021-12', '2022-01',
       '2022-02', '2022-03', '2022-04', '2022-05', '2022-06', '2022-07',
       '2022-08', '2022-09', '2022-10', '2022-11', '2022-12']

df_given_result = df_test[new_columns]

In [ ]:
df_given_result.to_csv("품목별 가격 데이터 최종.csv", encoding='cp949')